name = "G.I.M.P Pack"
author = "Cooks Corner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "639d04bbdbda01156d4e8b89aaef54eba22d319b1b87fdefad2cce3bed3fd2a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
