name = "Cooks Cosy Kitchen Pack"
author = "Cooks Corner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ef1bb4df082ee0eb9651df68fca7a31a81dbfc67c0932c4bcafa38d679901c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
