name = "Cooks Cosy Kitchen Pack"
author = "Cooks Corner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f88e289e0e28766d9e842bac34b0d952906cf30566b619b22e01e2b7330c1202"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
